services:
  johnwatson:
    build: .
    container_name: johnwatson

    ports:
      - "8000:8000"

    environment:
      PYTHONDONTWRITEBYTECODE: "1"

    volumes:
      - .:/app

    restart: unless-stopped
